import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { blockBegin, instructionsBlock, instructionsStatus, isImportOnly, majorMinor, planInstructions, writeInstructionsBlock } from "../src/init.js";

// PRD-embedded F-101: the CRT section for agents — its text, its markers, and where `crt init`
// puts it (every existing CLAUDE.md / AGENTS.md, an import-only CLAUDE.md skipped, created per
// provider when neither exists, replaced by markers, left alone on a matching stamp).

let tmp: string;
beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "crt-block-"));
});
afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

const read = (name: string) => readFileSync(join(tmp, name), "utf8");
const write = (name: string, text: string) => writeFileSync(join(tmp, name), text);
const BLOCK = instructionsBlock("0.4.0");

describe("the CRT section (F-101)", () => {
  it("is ≤ 15 lines, provider-neutral, LF only, with the versioned markers and the F-101 sentences", () => {
    const lines = BLOCK.split("\n");
    expect(lines.length).toBeLessThanOrEqual(15);
    expect(lines[0]).toBe("<!-- BEGIN:crt v0.4 -->");
    expect(lines[1]).toBe("## CRT (Claude Review Tool)");
    expect(lines.at(-1)).toBe("<!-- END:crt -->");
    expect(BLOCK).not.toContain("\r");
    for (const s of [
      "`.crt/` is part of this repository and is documented in `.crt/README.md`",
      "`.crt/tasks/*.md` are work items filed from the browser with CRT",
      "keep them, commit them with the project, never delete or \"clean up\" one",
      "`.crt/tasks/README.md` is generated by `crt tasks` — never hand-edit it",
      "`.crt/captures/` and `.crt/config.local.json` are per-machine and gitignored",
      "`/crt:next [ID]` in Claude Code, or read the task file — it is self-contained",
      "development-only and stays",
      "`crt init` maintains this section",
    ]) {
      expect(BLOCK).toContain(s);
    }
    // Provider-neutral (PRD-providers F-55 spirit): "in Claude Code" for /crt:next is the only Claude mention.
    expect(BLOCK.replace("## CRT (Claude Review Tool)", "").replace("in Claude Code", "")).not.toMatch(/\b(Claude|Codex|Gemini)\b/);
    expect(majorMinor("0.4.0")).toBe("0.4");
    expect(majorMinor("1.12.3")).toBe("1.12");
    expect(blockBegin("0.4.7")).toBe("<!-- BEGIN:crt v0.4 -->");
  });

  it("appends the block after a blank line to an existing CLAUDE.md and AGENTS.md alike (F-101)", () => {
    write("CLAUDE.md", "# My app\n\nRules.\n");
    write("AGENTS.md", "# Agents\nno trailing newline");
    const targets = writeInstructionsBlock(tmp, "claude", "0.4.0");
    expect(targets).toEqual([
      { file: "CLAUDE.md", action: "add" },
      { file: "AGENTS.md", action: "add" },
    ]);
    expect(read("CLAUDE.md")).toBe(`# My app\n\nRules.\n\n${BLOCK}\n`);
    expect(read("AGENTS.md")).toBe(`# Agents\nno trailing newline\n\n${BLOCK}\n`);
    // An empty file gets just the block.
    write("CLAUDE.md", "");
    writeInstructionsBlock(tmp, "claude", "0.4.0");
    expect(read("CLAUDE.md")).toBe(`${BLOCK}\n`);
  });

  it("skips a CLAUDE.md made only of @ import lines in favour of the file it imports (F-101)", () => {
    write("CLAUDE.md", "@AGENTS.md\n");
    write("AGENTS.md", "# Agents\n");
    expect(isImportOnly("@AGENTS.md\n")).toBe(true);
    expect(isImportOnly("@AGENTS.md\n\n@docs/rules.md\n")).toBe(true);
    expect(isImportOnly("# Title\n@AGENTS.md\n")).toBe(false);
    expect(isImportOnly("")).toBe(false);
    expect(writeInstructionsBlock(tmp, "claude", "0.4.0")).toEqual([{ file: "AGENTS.md", action: "add" }]);
    expect(read("CLAUDE.md")).toBe("@AGENTS.md\n");
    expect(read("AGENTS.md")).toBe(`# Agents\n\n${BLOCK}\n`);
    expect(instructionsStatus(tmp)).toEqual([{ file: "AGENTS.md", hasBlock: true }]);
  });

  it("creates CLAUDE.md for the claude provider and AGENTS.md otherwise when neither exists (F-101)", () => {
    expect(planInstructions(tmp, "claude", "0.4.0")).toEqual([{ file: "CLAUDE.md", action: "create" }]);
    expect(planInstructions(tmp, "codex", "0.4.0")).toEqual([{ file: "AGENTS.md", action: "create" }]);
    expect(planInstructions(tmp, "stub", "0.4.0")).toEqual([{ file: "AGENTS.md", action: "create" }]);
    writeInstructionsBlock(tmp, "codex", "0.4.0");
    expect(existsSync(join(tmp, "CLAUDE.md"))).toBe(false);
    expect(read("AGENTS.md")).toBe(`${BLOCK}\n`);
    rmSync(join(tmp, "AGENTS.md"));
    writeInstructionsBlock(tmp, "claude", "0.4.0");
    expect(read("CLAUDE.md")).toBe(`${BLOCK}\n`);
    // An import-only CLAUDE.md with nothing to import: AGENTS.md is created even for claude.
    write("CLAUDE.md", "@AGENTS.md\n");
    expect(planInstructions(tmp, "claude", "0.4.0")).toEqual([{ file: "AGENTS.md", action: "create" }]);
  });

  it("leaves a block with the same major.minor stamp alone, even when edited (F-101)", () => {
    const edited = `# App\n\n<!-- BEGIN:crt v0.4 -->\n## CRT (Claude Review Tool)\n\n- hand-edited text\n<!-- END:crt -->\n\nMore rules.\n`;
    write("CLAUDE.md", edited);
    expect(planInstructions(tmp, "claude", "0.4.3")).toEqual([{ file: "CLAUDE.md", action: "unchanged" }]);
    writeInstructionsBlock(tmp, "claude", "0.4.3");
    expect(read("CLAUDE.md")).toBe(edited);
  });

  it("regenerates the block in place by its markers when the stamp's major.minor differs, touching nothing around it (F-101)", () => {
    const old = `# App\n\n<!-- BEGIN:crt v0.3 -->\n## CRT (Claude Review Tool)\n\n- old text\n<!-- END:crt -->\n\nMore rules.\n`;
    write("CLAUDE.md", old);
    write("AGENTS.md", `Intro\n<!-- BEGIN:crt -->\nunstamped\n<!-- END:crt -->\n`);
    expect(writeInstructionsBlock(tmp, "claude", "0.4.0")).toEqual([
      { file: "CLAUDE.md", action: "update" },
      { file: "AGENTS.md", action: "update" },
    ]);
    expect(read("CLAUDE.md")).toBe(`# App\n\n${BLOCK}\n\nMore rules.\n`);
    expect(read("AGENTS.md")).toBe(`Intro\n${BLOCK}\n`);
    expect(read("CLAUDE.md").match(/<!-- BEGIN:crt/g)).toHaveLength(1);
    // A second run with the same version is a no-op.
    expect(writeInstructionsBlock(tmp, "claude", "0.4.0").every((t) => t.action === "unchanged")).toBe(true);
  });

  it("a marker mentioned inside a sentence is not a block: the section is appended, and a later run leaves the sentence intact (F-101)", () => {
    // This repository's CLAUDE.md names the markers in its Don'ts line.
    const dont = "- Don't write outside `.crt/` at runtime; `crt init` writes only inside the `<!-- BEGIN:crt -->` markers.\n- Don't send anything off-machine.\n";
    write("CLAUDE.md", dont);
    expect(planInstructions(tmp, "claude", "0.4.0")).toEqual([{ file: "CLAUDE.md", action: "add" }]);
    writeInstructionsBlock(tmp, "claude", "0.4.0");
    expect(read("CLAUDE.md")).toBe(`${dont}\n${BLOCK}\n`);
    expect(planInstructions(tmp, "claude", "0.4.0")).toEqual([{ file: "CLAUDE.md", action: "unchanged" }]);
    // An older stamp: only the block (own-line markers) is replaced; the sentence before it survives.
    write("CLAUDE.md", `${dont}\n${BLOCK.replace("v0.4", "v0.3")}\n`);
    expect(planInstructions(tmp, "claude", "0.4.0")).toEqual([{ file: "CLAUDE.md", action: "update" }]);
    writeInstructionsBlock(tmp, "claude", "0.4.0");
    expect(read("CLAUDE.md")).toBe(`${dont}\n${BLOCK}\n`);
    expect(instructionsStatus(tmp)).toEqual([{ file: "CLAUDE.md", hasBlock: true }]);
    write("CLAUDE.md", dont);
    expect(instructionsStatus(tmp)).toEqual([{ file: "CLAUDE.md", hasBlock: false }]);
  });

  it("writes LF only, converting a CRLF file it appends to (F-101, N-1)", () => {
    write("CLAUDE.md", "# App\r\n\r\nRules.\r\n");
    writeInstructionsBlock(tmp, "claude", "0.4.0");
    const text = read("CLAUDE.md");
    expect(text).not.toContain("\r");
    expect(text).toBe(`# App\n\nRules.\n\n${BLOCK}\n`);
  });

  it("instructionsStatus reports every existing target and whether it carries the markers (F-103, F-106)", () => {
    expect(instructionsStatus(tmp)).toEqual([]);
    write("CLAUDE.md", "# App\n");
    expect(instructionsStatus(tmp)).toEqual([{ file: "CLAUDE.md", hasBlock: false }]);
    write("AGENTS.md", `${BLOCK}\n`);
    expect(instructionsStatus(tmp)).toEqual([
      { file: "CLAUDE.md", hasBlock: false },
      { file: "AGENTS.md", hasBlock: true },
    ]);
  });
});
