/**
 * What `crt init` writes for the people and agents reading the repository (PRD-embedded F-100,
 * F-101, N-19): the `.crt/README.md` template, and the ≤ 15-line, provider-neutral CRT section it
 * keeps in `CLAUDE.md` / `AGENTS.md` between `<!-- BEGIN:crt vX.Y -->` and `<!-- END:crt -->`.
 * Those two files are `crt init`'s documented writes outside `.crt/`, and only inside the markers;
 * `crt doctor`'s `instructions` row reads `instructionsStatus`.
 */
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readText } from "./config.js";

export const README_FILE = "README.md";
export const REPO_URL = "https://github.com/simv/crt";

/**
 * F-100: the folder README for humans reading `.crt/` on GitHub. Written once, hand-editable
 * afterwards (never rewritten by a later `crt init`).
 */
export function readmeTemplate(version: string): string {
  return [
    "# .crt/ — Claude Review Tool",
    "",
    "CRT (Claude Review Tool) puts a review overlay on this project's local dev site: you annotate the page in the browser, talk to a coding agent in-page, and it writes a self-contained task file into this folder. Any later agent session completes a task from its file alone.",
    "",
    "## What is in this folder",
    "",
    "- `tasks/` — the work items, one Markdown file each (`CRT-NNNN-<slug>.md`): YAML frontmatter (`id`, `title`, `status`, `priority`, dates, `url`, `route`, `tags`, `files`), then Summary, Context, Evidence, Ask, Definition of Done, Notes and Log. Statuses run `backlog → in_progress → review → done` (or `blocked`).",
    "- `tasks/README.md` — the generated index; `crt tasks` rewrites it, never hand-edit it.",
    "- `tasks/assets/<ID>/` — the screenshots a task's Evidence refers to.",
    "- `captures/` — transient page captures waiting for intake; gitignored, pruned after 7 days.",
    "- `config.json` — committed, per project: `mode` (`embedded` or `proxy`), `target` (the app URL), `port` (the CRT server port), `provider` (the agent).",
    '- `config.local.json` — the same keys per machine (what "Remember" and the guided start write); gitignored.',
    "",
    "## Working a task",
    "",
    "- `/crt:next [ID]` in Claude Code takes the next backlog task (or the named one) to an open pull request.",
    "- `crt tasks` lists the tasks; `crt task <ID>` prints one (`--validate` checks its format).",
    "- A task file is self-contained: any agent can read it and do the work.",
    "",
    `Written by crt init ${version}; ${REPO_URL}`,
    "",
  ].join("\n");
}

// ---- the CRT section for agents (F-101) --------------------------------------------------------------

/** The agent instruction files `crt init` maintains a section in, in the order they are checked. */
export const INSTRUCTION_FILES = ["CLAUDE.md", "AGENTS.md"] as const;
export type InstructionFile = (typeof INSTRUCTION_FILES)[number];
export const BLOCK_END = "<!-- END:crt -->";
/**
 * Matches one existing block, capturing its major.minor stamp (absent in a hand-made block). Both
 * markers must stand on their own lines: a sentence that merely mentions `<!-- BEGIN:crt -->` (this
 * repository's CLAUDE.md does) is not a block.
 */
const BLOCK_RE = /^<!-- BEGIN:crt(?: v(\d+\.\d+)(?:\.\d+)?)? -->[ \t]*\r?\n[\s\S]*?^<!-- END:crt -->[ \t]*$/m;

/** `0.4.0` → `0.4`; the stamp the markers carry and the comparison that decides regeneration. */
export function majorMinor(version: string): string {
  const m = /^(\d+)\.(\d+)/.exec(version);
  return m ? `${m[1]}.${m[2]}` : version;
}

export function blockBegin(version: string): string {
  return `<!-- BEGIN:crt v${majorMinor(version)} -->`;
}

/** F-101: the section text (≤ 15 lines, provider-neutral), between its markers, LF only, no trailing newline. */
export function instructionsBlock(version: string): string {
  return [
    blockBegin(version),
    "## CRT (Claude Review Tool)",
    "",
    "- `.crt/` is part of this repository and is documented in `.crt/README.md`.",
    '- `.crt/tasks/*.md` are work items filed from the browser with CRT. They can appear while a CRT intake session runs — that is expected: keep them, commit them with the project, never delete or "clean up" one.',
    "- `.crt/tasks/README.md` is generated by `crt tasks` — never hand-edit it.",
    "- `.crt/captures/` and `.crt/config.local.json` are per-machine and gitignored.",
    "- To work a task: `/crt:next [ID]` in Claude Code, or read the task file — it is self-contained.",
    "- The CRT integration in the app (one dev-only import, printed by `crt init`) is development-only and stays.",
    "- `crt init` maintains this section.",
    BLOCK_END,
  ].join("\n");
}

/** A `CLAUDE.md` made only of `@` import lines (the trial app's `@AGENTS.md`) — skipped in favour of what it imports. */
export function isImportOnly(text: string): boolean {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  return lines.length > 0 && lines.every((l) => l.startsWith("@"));
}

export interface InstructionsTarget {
  file: InstructionFile;
  /** `create` when neither file exists; `add` appends; `update` replaces a block with another major.minor; `unchanged` leaves a matching stamp alone. */
  action: "create" | "add" | "update" | "unchanged";
}

/** What `writeInstructionsBlock` would do, file by file (the plan reads it; the doctor's `instructions` row reads `instructionsStatus`). */
export function planInstructions(root: string, provider: string, version: string): InstructionsTarget[] {
  const out: InstructionsTarget[] = [];
  for (const file of INSTRUCTION_FILES) {
    const text = readText(join(root, file));
    if (text === null) continue;
    if (file === "CLAUDE.md" && isImportOnly(text)) continue;
    const m = BLOCK_RE.exec(text);
    out.push({ file, action: m === null ? "add" : m[1] === majorMinor(version) ? "unchanged" : "update" });
  }
  if (!out.length) out.push({ file: provider === "claude" && !existsSync(join(root, "CLAUDE.md")) ? "CLAUDE.md" : "AGENTS.md", action: "create" });
  return out;
}

/**
 * F-101: write the section into every target — appended after a blank line, replaced in place by
 * its markers when the stamped major.minor differs, left alone when it matches (even if edited),
 * created as `CLAUDE.md` for `claude` and `AGENTS.md` otherwise when neither exists. LF only.
 */
export function writeInstructionsBlock(root: string, provider: string, version: string): InstructionsTarget[] {
  const block = instructionsBlock(version);
  const targets = planInstructions(root, provider, version);
  for (const t of targets) {
    const path = join(root, t.file);
    if (t.action === "unchanged") continue;
    if (t.action === "create") {
      writeFileSync(path, `${block}\n`, "utf8");
      continue;
    }
    const text = readText(path) ?? "";
    if (t.action === "update") {
      writeFileSync(path, text.replace(BLOCK_RE, block), "utf8");
      continue;
    }
    const body = text.replace(/\r\n/g, "\n");
    const gap = body === "" ? "" : body.endsWith("\n\n") ? "" : body.endsWith("\n") ? "\n" : "\n\n";
    writeFileSync(path, `${body}${gap}${block}\n`, "utf8");
  }
  return targets;
}

/** The existing instruction files (an import-only `CLAUDE.md` skipped) and whether each carries the markers — the doctor's `instructions` row and the F-106 hook. */
export function instructionsStatus(root: string): Array<{ file: InstructionFile; hasBlock: boolean }> {
  const out: Array<{ file: InstructionFile; hasBlock: boolean }> = [];
  for (const file of INSTRUCTION_FILES) {
    const text = readText(join(root, file));
    if (text === null) continue;
    if (file === "CLAUDE.md" && isImportOnly(text)) continue;
    out.push({ file, hasBlock: BLOCK_RE.test(text) });
  }
  return out;
}
